Label Encoding 

Label encoding and ordinal encoding are two techniques used to encode categorical data as numericla data.

Label encoding involves assigning a unique numerical label to each categories in the variable. The labels are usually assingned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green ,blue) we can represent it using label encoding as follows:

1. Red 1
2. Green 2
3. Blue 3

In [2]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

In [3]:
## Create a simple dataframe 

df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'blue', 'red']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3   blue
4    red

In [5]:
lbl_encoder = LabelEncoder()

In [6]:
encoded = lbl_encoder.fit_transform(df[['color']])
print(encoded)

[2 0 1 0 2]

c:\Users\Eng\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [7]:
## for adding  new values 
lbl_encoder.transform([['blue']])

c:\Users\Eng\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

#### Ordinal encoding 
when we have to decide the rank or order. In this technique, each category is assigned a numerical value based on its positioiin in the order. Example if we have a cstegorical variable " education level" with four possible values 

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-Grauduate: 4

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large','small', 'medium', 'large', 'small', 'large']
})

In [11]:
df

     size
0   small
1  medium
2   large
3   small
4  medium
5   large
6   small
7   large

In [12]:
## assigning ranking 
encoder = OrdinalEncoder(categories= [['small', 'medium', 'large']])

In [13]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.]])

In [15]:
print(encoder.transform([['small']]))

[[0.]]

c:\Users\Eng\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(